version: '3'
services:
  web3indexer:
    container_name: web3indexer
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:7.0.7-alpine