version: '3'
services:
  web3indexer:
    container_name: web3indexer
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
  redis:
    container_name: redis
    image: redis:7.0.7-alpine
    ports:
      - "6379:6379"